import type { Metadata } from "next";
import { Ubuntu_Condensed } from "next/font/google";
import "./globals.css";
import GraphqlProvider from "@/components/providers/GraphqlProvider";

const geistSans = Ubuntu_Condensed({
    weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans} antialiased`}
      >
        <GraphqlProvider>
            {children}
        </GraphqlProvider>
      </body>
    </html>
  );
}
