import type { Metadata } from "next";
import { Ubuntu_Condensed } from "next/font/google";
import "./globals.css";
import GraphqlProvider from "@/components/providers/GraphqlProvider";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

const geistSans = Ubuntu_Condensed({
	weight: "400",
});

export const metadata: Metadata = {
	title: "Lexicon",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans} antialiased`}>
				<GraphqlProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</GraphqlProvider>
			</body>
		</html>
	);
}
